### ISSUE TITLE
List of commands that can be used?

### ISSUE THREAD

**Issue by BleepLogger** [bernd-wechner/Degoo#24]
Hello, this project is a few months old and has most likely been abandoned. However, I'm not actually able to find clear instructions or documentation. I'd love it if the devs could help me out.
How exactly do I use it? So far I've gathered that I:
1. Enter the directory with `cd ~/Downloads/degoo/`
2. Add the packages with `pip install -r requirements.txt`
3. Build it with `python3.9 build.py`

But what do I do that? Now that I've built the commands, I need to know what the commands are! For example, if I wanted to upload a file located in the path `~/image.jpg` to my degoo account, how would I do this?
Where can I get any docs related to this?

**Comment by BleepLogger** [comment]
I read the whole source code just now but I still don't have any idea how to use this. Please help me. How to upload and download files? I just need to know what command to run. Any sort of documentation would be appreciated.

**Comment by bernd-wechner** [comment]
It's far from abandoned. It's just not a top priority. I am developing it for use as a back up tool myself, but have not yet implemented it for that. Not least as I am very busy on competing jobs. It's been blessed with some interest and contributions from other lately too. I admit it's a puzzle to me why something looks abandoned just because the last code change was 2 months ago ;-). If you got zero reply to an issue, then I'd start thinking it was abandoned ;-). Many a viable project is stable and sees no code updates for a long long time. This one however is in evolution ... just not got much dedicated development time (in fact I turn away from my kids and a math refactor on a TrueSkill document to answer you ;-).

Of course, it is also on github and admittedly a personal project not a published tool. It lacks an installer, it lacks versioning and it lacks as you noticed a solid readme and handhold.

That said, I'd generally on encountering such a project (as I do), 

1. Fork it (top right of Github page)
2. Clone it (Code page on Github has a Code button for this, top right again of the Code area)
3. And then experiment

Anyhow, there are not basic docs yet, it's all internally documented, and with a caveat emptor ;-)

But that said, all testing and feedback is very welcome! 

If you can build.py successfully you should probably have found a lot of degoo_ files in your working directory. These implement a pile of familiar paradigms. I would typically start with `degoo_login` and see what happens. After that I'd experiment with `degoo_ls` to see what it can report on my remote degood file system. And finally `degoo_get` and `degoo_put` for download from and upload to a degoo account.

Hope that helps ...  Improvements to the `README.md` always welcome!

Good luck, back to math for me.

**Comment by BleepLogger** [comment]
Thank you so much. I read the source code and experimented it out, and it's working well. Sorry for assuming that this project was abandoned.

**Comment by bernd-wechner** [comment]
No worries. Hope it does. I'm sort of hoping still to see if Degoo won't provide me with a way of getting a remote file hash. I hope to set it up as a background backup synchroniser in time. It's close to providing that but I keep getting distracted ;-).
