### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by gargola-dev** [bernd-wechner/Degoo#37]
I am currently setting degoo on my RPI and have the following issue: 

zeus@rpi-3b ~/src/Degoo (master*) $ python build.py 
Traceback (most recent call last):
  File "build.py", line 20, in <module>
    import degoo
  File "/home/zeus/src/Degoo/degoo/__init__.py", line 41, in <module>
    from .util import *
  File "/home/zeus/src/Degoo/degoo/util.py", line 136
    print(f"Waiting until {until.strftime('%A, %d/%m/%Y %H:%M:%S')}")

How should I proceed?

**Comment by bernd-wechner** [comment]
Hey, @gargola-dev, my sincere apologies for a rather tardy response. I guess it should be no surprise that December is a tough time to get the attention of volunteers who turn to the whole Xmas and New year proceedings ;-). 

Impossible to be sure what your problem is because you failed to copy the actual error message. All you've shown is the traceback. As a general rule it's good to surround code too with three backticks, which are inserted on github easily with the toolbar code button. BUt your code would them resemble:

```
zeus@rpi-3b ~/src/Degoo (master*) $ python build.py
Traceback (most recent call last):
File "build.py", line 20, in
import degoo
File "/home/zeus/src/Degoo/degoo/init.py", line 41, in
from .util import *
File "/home/zeus/src/Degoo/degoo/util.py", line 136
print(f"Waiting until {until.strftime('%A, %d/%m/%Y %H:%M:%S')}")
```
which simply improves legibility a bit.

That aside, the last line does lend a clue. In that it includes f -string. These are a relatively new Python feature (from 3.6):

https://datagy.io/python-f-strings/

and a simple guess is you're using an older version of python so try this: `python --version`. On my box right now:

```
$ python --version
Python 3.8.10
```
and these tools demand 3.9 or better according to the README.

**Comment by bernd-wechner** [comment]
Closing as stale. No response since Jan.
