### ISSUE TITLE
response 400 for all commands

### ISSUE THREAD

**Issue by MirroredAura** [bernd-wechner/Degoo#44]
I'm getting this every time now it was working fine a few weeks ago. I updated to the newest version and still get this.

```
Traceback (most recent call last):
  File "/tmp/degoo2/./degoo_ls", line 328, in <module>
    sys.exit(main())
  File "/tmp/degoo2/./degoo_ls", line 116, in main
    degoo.ls(args.folder, args.long, args.human, args.recursive)
  File "/tmp/degoo2/degoo/util.py", line 1210, in ls
    items = get_children(directory)
  File "/tmp/degoo2/degoo/util.py", line 604, in get_children
    __CACHE_CONTENTS__[dir_id] = api.getFileChildren3Ex(dir_id)
  File "/tmp/degoo2/degoo/API.py", line 659, in getFileChildren3Ex
    (next_items, next_token) = self.getFileChildren3(dir_id, next_token)
  File "/tmp/degoo2/degoo/API.py", line 650, in getFileChildren3
    raise self.Error(f"getFileChildren3 failed with: {response}")
degoo.API.API.Error: getFileChildren3 failed with: <Response [400]>
degoo_ls: getFileChildren3 failed with: <Response [400]>
          for help use --help
```

**Comment by bernd-wechner** [comment]
Interesting. Alas my workstation died in sympathy as our whole family went down with COVID (or it was first case of COVID 19 infecting a motherboard) and so I am out action until late May at best guess currently (am rebuilding the work station but using the break to get a lot of other - real world - stuff done - as in I'm building a a bike shed).

400 suggests a bad request. The problem is having reverse engineered the API Degoo are free to change it any time (the API that is), they don't document it or support it. So I would encourage you to attempt a diagnosis. The README has steps from memory you can follow using any browser and it's built in debug tools and all I do is execute the desire action on the Degoo website while recording the HTTP traffic. The result that I've implemented mimics what I saw.
