### ISSUE TITLE
degoo_get: download() got an unexpected keyword argument 'size'

### ISSUE THREAD

**Issue by MDKPredator** [bernd-wechner/Degoo#6]
When I try to download a file I get the error **download() got an unexpected keyword argument 'size'**, both in Windows and Ubuntu. I have seen that you need to install https://github.com/bernd-wechner/python3-wget 

Honestly, I haven't tried to install this package, but I think that to avoid this error for new users you could download it as standard with requests:

          if not dry_run:
              # _ = wget.download(URL, out=Name, size=Size, headers={'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/83.0.4103.61 Chrome/83.0.4103.61 Safari/537.36"})
              silent = False # It could be a new argument
              with requests.get(URL, stream=True) as r:
                  r.raise_for_status()
                  with open(Name, 'wb') as f:
                      if silent:
                          shutil.copyfileobj(r.raw, f)
                      else:
                          dl = 0
                          total_length = int(r.headers.get('content-length'))
                          if not total_length:
                              total_length = Size
                          for data in r.iter_content(chunk_size=4096):
                              dl += len(data)
                              f.write(data)
                              done = int(50 * dl / total_length)
                              sys.stdout.write("\r[%s%s]" % ('=' * done, ' ' * (50-done)))
                              sys.stdout.flush()

I hope it will be helpful.

**Comment by GrowtopiaJaw** [comment]
This is interesting. At first, I was facing this error and I never came across this custom [python3-wget](https://github.com/bernd-wechner/python3-wget). Something like this would really be useful especially for new users as you've said.

**Comment by bernd-wechner** [comment]
Yes indeed. I had to patch python3-wget because it's download progress was broken and the package seems unmaintained alas. Normally (often) on a file download there's a header in the HTTP request that informs wget of the filesize and it displays a progress bar accordingly. Alas when that header is absent the progress bar renders but in a broken way. Degoo downloads don't provide that header. BUT the Degoo file metadata doe share the filsesize so we can tell wget what the expected filesize is, and that's what the patch does.

Clearly that package is a prerequisite as a result.

**Comment by bernd-wechner** [comment]
`requirements.txt` now merged into the project.
